title: Blog of Cameron
author: cam3154
email: cameronmoore3131@gmail.com
description: > This page will be a blog about me and about all of the things I do.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  cam3154

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
